/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.geospace.view;


import ec.edu.espe.geospace.controller.GeoSpaceController;
import ec.edu.espe.geospace.controller.GeoSpaceController1;
import ec.edu.espe.geospace.controller.GeoSpaceController2;
import ec.edu.espe.geospace.model.GeoSpace;
import ec.edu.espe.geospace.model.GeoSpace1;
import ec.edu.espe.geospace.model.GeoSpace2;
import java.io.FileNotFoundException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.FileManager;

/**
 *
 * @author User
 */
public class FrmGeoSpace extends javax.swing.JFrame {

    /**
     * Creates new form FrmGeoSpace
     */
    public FrmGeoSpace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        txtDistance1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCoordinateX2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtCoordinateY3 = new javax.swing.JTextField();
        cmbResult3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnASave1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtCoordinatex3 = new javax.swing.JTextField();
        txtResult1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtResult3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtCoordinateY4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblCoordinatesPolar1 = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnShowPolar1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        btnFindCoordinate1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtRectangularCoordinateX1 = new javax.swing.JTextField();
        txtCoordinateName1 = new javax.swing.JTextField();
        txtRectangularCoordinateY1 = new javax.swing.JTextField();
        btnCoordinatePolar1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtCoordinatePolar1 = new javax.swing.JTextField();
        txtAngle1 = new javax.swing.JTextField();
        cmbOptions1 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnSaveAzimut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCoordinateY2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAngle = new javax.swing.JTextField();
        cmbOrientation = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtDistance = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCoordinateX1 = new javax.swing.JTextField();
        txtCoordinateY1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCoordinatex2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblCoordinatesPolar = new javax.swing.JTable();
        btnShowCoordinate3 = new javax.swing.JButton();
        btnFindCoordinate3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCoordinateNumber = new javax.swing.JTextField();
        btnCoordinatePolar = new javax.swing.JButton();
        txtCoordinatePolar = new javax.swing.JTextField();
        btnCoordinateRectangular = new javax.swing.JButton();
        txtCoordinateRectangular = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCoordinatesRectangular = new javax.swing.JTable();
        btnShow = new javax.swing.JButton();
        btnFindCoordinate2 = new javax.swing.JButton();
        txtFind2 = new javax.swing.JTextField();
        btnResult = new javax.swing.JButton();
        txtResult2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRectangularCoordinateX = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtRectangularCoordinateY = new javax.swing.JTextField();
        txtNumberOfTransformation = new javax.swing.JTextField();
        txtCoordinateFind = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblGeographic = new javax.swing.JTable();
        btnShowRectangularToGeographic = new javax.swing.JButton();
        btnFindCoordinate = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtFindACoordinate = new javax.swing.JTextField();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel18.setText("Rectangular coordinate x:");

        jLabel19.setText("Rectangular coordinate y:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setText("Coordinate B");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setText("Coordinate A");

        cmbResult3.setText("Result ");

        jLabel22.setText("Rectangular coordinate x:");

        btnASave1.setText("Save");
        btnASave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnASave1ActionPerformed(evt);
            }
        });

        jLabel23.setText("Rectangular coordinate y:");

        jButton4.setText("Result ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("                    UNIVERSIDAD DE LAS FUERZAS ARMADAS (ESPE)    ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setText("Engineering in Geospatial Technologies ");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("1. Rectangular to Geographic Coordinates");

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel27.setText("TRANSFORMATION OF COORDINATES");

        tblCoordinatesPolar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coordinate name", "Coordinate X1", "Coordinate Y1", "Coordinate X2", "Coordinate Y2", "Coordinate "
            }
        ));
        jScrollPane6.setViewportView(tblCoordinatesPolar1);
        if (tblCoordinatesPolar1.getColumnModel().getColumnCount() > 0) {
            tblCoordinatesPolar1.getColumnModel().getColumn(0).setResizable(false);
            tblCoordinatesPolar1.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("2.Geographic Coordinates to Rectangular");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("3. Rectangular to Polar coordinates");

        btnShowPolar1.setText("Show ");
        btnShowPolar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPolar1ActionPerformed(evt);
            }
        });

        jLabel30.setText("Rectangular coordinate x:");

        btnFindCoordinate1.setText("Find a coordinate");
        btnFindCoordinate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCoordinate1ActionPerformed(evt);
            }
        });

        jLabel31.setText("Rectangular coordinate y:");

        jLabel32.setText("Coordinate name");

        btnCoordinatePolar1.setText("Coordinate Polar");
        btnCoordinatePolar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoordinatePolar1ActionPerformed(evt);
            }
        });

        jLabel33.setText("Distance");

        cmbOptions1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. North-East (NE) ", "2. North-West (NO) ", "3. South-West (SO) ", "4. South-East (SE)" }));

        jLabel34.setText("Angle");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("Coordinate B");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Coordinate A");

        btnSaveAzimut.setText("Save");
        btnSaveAzimut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAzimutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("1. Rectangular to Geographic Coordinates");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("2.Geographic Coordinates to Rectangular");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("3. Rectangular to Polar coordinates");

        jLabel7.setText("Distance:");

        cmbOrientation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "North-East (NE)", "North-West (NO)", "South-West (SO)", "South-East (SE)" }));

        jLabel8.setText("Angle:");

        jLabel9.setText("Rectangular coordinate x:");

        jLabel10.setText("Rectangular coordinate y:");

        jLabel11.setText("Rectangular coordinate x:");

        jLabel12.setText("Rectangular coordinate y:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("                    UNIVERSIDAD DE LAS FUERZAS ARMADAS (ESPE)    ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Engineering in Geospatial Technologies ");

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel17.setText("TRANSFORMATION OF COORDINATES");

        tblCoordinatesPolar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coordinate name", "Coordinate X1", "Coordinate Y1", "Coordinate X2", "Coordinate Y2", "Coordinate "
            }
        ));
        jScrollPane5.setViewportView(tblCoordinatesPolar);
        if (tblCoordinatesPolar.getColumnModel().getColumnCount() > 0) {
            tblCoordinatesPolar.getColumnModel().getColumn(0).setResizable(false);
            tblCoordinatesPolar.getColumnModel().getColumn(1).setResizable(false);
        }

        btnShowCoordinate3.setText("Show ");
        btnShowCoordinate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCoordinate3ActionPerformed(evt);
            }
        });

        btnFindCoordinate3.setText("Find a coordinate");
        btnFindCoordinate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCoordinate3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Coordinate Number");

        btnCoordinatePolar.setText("Coordinate Polar");
        btnCoordinatePolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoordinatePolarActionPerformed(evt);
            }
        });

        btnCoordinateRectangular.setText("Coordinate Rectangular");
        btnCoordinateRectangular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoordinateRectangularActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tblCoordinatesRectangular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Distance", "Orientation", "Angle", "Coordinate X", "Coordinate Y"
            }
        ));
        jScrollPane1.setViewportView(tblCoordinatesRectangular);

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnFindCoordinate2.setText("Find a coordinate");
        btnFindCoordinate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCoordinate2ActionPerformed(evt);
            }
        });

        btnResult.setText("Result ");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        jLabel5.setText("Rectangular coordinate x:");

        jLabel6.setText("Rectangular coordinate y:");

        jLabel35.setText("Number of transformation times: ");

        jLabel36.setText("Coordinate X or Y to find :");

        tblGeographic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transform N°", "Coordinate X", "Coordinate Y", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblGeographic);

        btnShowRectangularToGeographic.setText("Show ");
        btnShowRectangularToGeographic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowRectangularToGeographicActionPerformed(evt);
            }
        });

        btnFindCoordinate.setText("Find a coordinate");
        btnFindCoordinate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCoordinateActionPerformed(evt);
            }
        });

        jLabel37.setText("Orientation:");

        jLabel38.setText("Find a Coordinate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(605, 605, 605)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(765, 1382, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnResult)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtResult2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel36)
                                    .addGap(38, 38, 38)
                                    .addComponent(txtCoordinateFind, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel35)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNumberOfTransformation, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRectangularCoordinateY))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRectangularCoordinateX, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel7)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(jLabel8)
                                                            .addGap(58, 58, 58)
                                                            .addComponent(txtAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel37)
                                                        .addGap(27, 27, 27)
                                                        .addComponent(cmbOrientation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(85, 85, 85)
                                                        .addComponent(btnSave)))
                                                .addGap(48, 48, 48)))
                                        .addGap(240, 240, 240))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnCoordinateRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnFindCoordinate2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCoordinateRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFind2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCoordinatex2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel10))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCoordinateY1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jLabel9))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtCoordinateX1)
                                                        .addComponent(txtCoordinateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnSaveAzimut)
                                                        .addComponent(jLabel12))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCoordinateY2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnCoordinatePolar)
                                                        .addComponent(jLabel38))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtCoordinatePolar)
                                                        .addComponent(txtFindACoordinate))))
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnShowCoordinate3)
                                                .addGap(142, 142, 142)
                                                .addComponent(btnFindCoordinate3)))))))
                        .addGap(198, 198, 198))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnShowRectangularToGeographic)
                                .addGap(58, 58, 58)
                                .addComponent(btnFindCoordinate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnShow)
                                .addGap(238, 238, 238)))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtCoordinateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtCoordinateX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtCoordinateY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtCoordinatex2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCoordinateRectangular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCoordinateRectangular)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbOrientation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCoordinateY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(btnSave)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnFindCoordinate2)
                                    .addComponent(txtFind2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnShow)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnSaveAzimut)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCoordinatePolar)
                                    .addComponent(txtCoordinatePolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel38)
                                    .addComponent(txtFindACoordinate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnShowCoordinate3))
                                    .addComponent(btnFindCoordinate3))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txtNumberOfTransformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtRectangularCoordinateX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtRectangularCoordinateY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResult)
                            .addComponent(txtResult2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCoordinateFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnShowRectangularToGeographic)
                            .addComponent(btnFindCoordinate))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveAzimutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAzimutActionPerformed
        GeoSpace geoSpace;
        double coordinateNumber;
        double[] integers;
        double azimutResult;
        double azimut = 0;
        double variationX = 0;
        double variationY = 0;
        int coordinatePolar = 0;
        String transformation = "";
        Vector polar = new Vector();
        integers = new double[4];

        coordinateNumber = Double.parseDouble(txtCoordinateNumber.getText());
        integers[0] = Integer.parseInt(txtCoordinateX1.getText());
        integers[1] = Integer.parseInt(txtCoordinateY1.getText());
        integers[2] = Integer.parseInt(txtCoordinatex2.getText());
        integers[3] = Integer.parseInt(txtCoordinateY2.getText());

        GeoSpaceController geoSpaceController = new GeoSpaceController();

        variationX = integers[2] - integers[0];
        variationY = integers[3] - integers[1];
        azimut = Math.atan(variationX / variationY);
        azimut = azimut + 360;
        azimutResult = geoSpaceController.transformGeographicCoordinatesToPolar(integers[0], integers[1], integers[2], integers[3]);

        if (variationX > 0 & variationY >= 0) {
            transformation = "" + String.format("%.2f", azimutResult);
        }
        if (variationX > 0 & variationY <= 0) {
            transformation = "" + String.format("%.2f", azimutResult);
        }
        if (variationX < 0 & variationY > 0) {
            azimut = azimut - 180;
            transformation = "" + String.format("%.2f", azimutResult);
        }
        if (variationX < 0 & variationY < 0) {
            azimut = azimut + 180;
            transformation = "" + String.format("%.2f", azimutResult);
        }

        geoSpace = new GeoSpace(coordinateNumber, integers[0], integers[1], integers[2], integers[3], azimutResult, coordinatePolar);
        geoSpaceController.saveRectangularToPolarCoordinates(geoSpace);
        DefaultTableModel table;
        polar.addElement("Coordinate number");
        polar.addElement("Coordinate X1");
        polar.addElement("Coordinate Y1");
        polar.addElement("Coordinate X2");
        polar.addElement("Coordinate Y2");
        polar.addElement("Coordinate Polar");


    }//GEN-LAST:event_btnSaveAzimutActionPerformed

    private void btnShowCoordinate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCoordinate3ActionPerformed
        try {
            GeoSpaceController geoSpaceController = new GeoSpaceController();
            tblCoordinatesPolar.setModel(geoSpaceController.readRectangularToPolarCoordinates());
        } catch (FileNotFoundException e) {
            Logger.getLogger(FrmGeoSpace.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnShowCoordinate3ActionPerformed

    private void btnFindCoordinate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCoordinate3ActionPerformed
       GeoSpaceController geoSpace = new GeoSpaceController();

        int[] integers;
        int dataToFind;
        int index = 0;
        integers = new int[4];

        dataToFind = Integer.parseInt(txtFindACoordinate.getText());
        integers[0] = Integer.parseInt(txtCoordinateX1.getText());
        integers[1] = Integer.parseInt(txtCoordinateY1.getText());
        integers[2] = Integer.parseInt(txtCoordinatex2.getText());
        integers[3] = Integer.parseInt(txtCoordinateY2.getText());
        index = geoSpace.findCoordinate(dataToFind, integers);

        if (index == -1) {
            JOptionPane.showMessageDialog(null, dataToFind + " is NOT found ", "Searching", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, dataToFind + " is found ");
        }


    }//GEN-LAST:event_btnFindCoordinate3ActionPerformed

    private void btnCoordinatePolarActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        GeoSpace geoSpace;
        double[] integers;
        double azimutResult;
        integers = new double[4];
        String transformationToSexagesimals;
        
        integers[0] = Integer.parseInt(txtCoordinateX1.getText());
        integers[1] = Integer.parseInt(txtCoordinateY1.getText());
        integers[2] = Integer.parseInt(txtCoordinatex2.getText());
        integers[3] = Integer.parseInt(txtCoordinateY2.getText());

        GeoSpaceController geoSpaceController = new GeoSpaceController();

        azimutResult = geoSpaceController.transformGeographicCoordinatesToPolar(integers[0], integers[1], integers[2], integers[3]);
        int degrees = (int) azimutResult;
        double fractionalDegrees = azimutResult - degrees;
        double minutesWithFraction = 60 * fractionalDegrees;
        int minutes = (int) minutesWithFraction;
        double fractionalMinutes = minutesWithFraction - minutes;
        double secondsWithFraction = 60 * fractionalMinutes;
        int seconds = (int) Math.round(secondsWithFraction);
        transformationToSexagesimals = degrees + "°" + minutes + "'" + seconds + "'' ";
        txtCoordinatePolar.setText(transformationToSexagesimals);
    }	                                                  
    
    
    private void btnASave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnASave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnASave1ActionPerformed

    private void btnShowPolar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPolar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowPolar1ActionPerformed

    private void btnFindCoordinate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCoordinate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindCoordinate1ActionPerformed

    private void btnCoordinatePolar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoordinatePolar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoordinatePolar1ActionPerformed

    private void btnCoordinateRectangularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoordinateRectangularActionPerformed

        double distance;
        double angle;
        String orientation;
        int coordinateRectangular = 0;
        double X = 0;
        double Y = 0;
        String transformation = null;
        
        distance = Double.parseDouble(txtDistance.getText());
        orientation = cmbOrientation.getSelectedItem().toString();
        angle = Double.parseDouble(txtAngle.getText());
        GeoSpaceController2 geoSpaceController2 = new GeoSpaceController2();
        double angler = Math.toRadians(angle);
        double anglerx = Math.sin(angler);
        double anglery = Math.cos(angler);
        X = distance * anglerx;
        Y = distance * anglery;

        if (cmbOrientation.getSelectedItem().equals("North-East (NE)")) {
            transformation = ("X = " + String.format("%.2f", X) + ",  Y = " + String.format("%.2f", Y));
        } else if(cmbOrientation.getSelectedItem().equals("North-West (NO)")) {
            transformation = ("X = -" + String.format("%.2f", X) + ",  Y = " + String.format("%.2f", Y));            
        } else if(cmbOrientation.getSelectedItem().equals("South-West (SO)")) {
            transformation = ("X = -" + String.format("%.2f", X) + ",  Y = -" + String.format("%.2f", Y));           
        } else if(cmbOrientation.getSelectedItem().equals("South-East (SE)")) {
            transformation = ("X = " + String.format("%.2f", X) + ",  Y = -" + String.format("%.2f", Y));
        }
        txtCoordinateRectangular.setText(transformation);
    }//GEN-LAST:event_btnCoordinateRectangularActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        GeoSpace2 geoSpace2 = null;
        double distance;
        double angle;
        String orientation;
        double X = 0;
        double Y = 0;
        int coordinateRectangular = 0;

        Vector rectangular = new Vector();

        distance = Double.parseDouble(txtDistance.getText());
        orientation = cmbOrientation.getSelectedItem().toString();
        angle = Double.parseDouble(txtAngle.getText());

        GeoSpaceController2 geoSpaceController2 = new GeoSpaceController2();
        double angler = Math.toRadians(angle);
        double anglerx = Math.sin(angler);
        double anglery = Math.cos(angler);
        X = distance * anglerx;
        Y = distance * anglery;

        geoSpace2 = new GeoSpace2(distance, angle, orientation, X, Y);
        geoSpaceController2.saveGeographicCoordinatesToRectangular(geoSpace2);
        DefaultTableModel table;
        rectangular.addElement("Distance");
        rectangular.addElement("Orientation");
        rectangular.addElement("Angle");
        rectangular.addElement("Coordinate X");
        rectangular.addElement("Coordinate Y");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed

        try {
            GeoSpaceController2 geoSpaceController2 = new GeoSpaceController2();
            tblCoordinatesRectangular.setModel(geoSpaceController2.readGeographicCoordinatesToRectangular());
        } catch (FileNotFoundException e) {
            Logger.getLogger(FrmGeoSpace.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnFindCoordinate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCoordinate2ActionPerformed

        int index = 0;
        GeoSpaceController2 find = new GeoSpaceController2();
        int[] integers;
        int dataToFind;
        
        integers = new int[2];
        
        dataToFind = Integer.parseInt(txtFind2.getText());
        integers[0] = Integer.parseInt(txtDistance.getText());
        integers[1] = Integer.parseInt(txtAngle.getText());
        
        index = find.findCoordinate2(dataToFind, integers);
        
        if(index == -1){
            JOptionPane.showMessageDialog(null,dataToFind + " is NOT found ","Searching", JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, dataToFind + " is found ");
        }
                         
    }//GEN-LAST:event_btnFindCoordinate2ActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        GeoSpace1 geoSpace;
        double angleF1 = 0;
        double angleF2 = 0;
        int numberOfTransformation;

        double c = 0;
        double result;
        double[] integers;
        String transformation = "";
        double Angle1;
        double Angle2;
        Vector polar = new Vector();
        integers = new double[2];
        integers[0] = Integer.parseInt(txtRectangularCoordinateX.getText());
        integers[1] = Integer.parseInt(txtRectangularCoordinateY.getText());
        numberOfTransformation= Integer.parseInt(txtNumberOfTransformation.getText());
        GeoSpaceController1 transform = new GeoSpaceController1();
        result = transform.transformRectangularToGeographicCoordinates(integers[0], integers[1], c);
        Angle1 = transform.calculateAngle1(integers[0], integers[1], angleF1);
        Angle2 = transform.calculateAngle2(integers[0], integers[1], angleF2);

        if (integers[0] > 0 && integers[1] > 0) {
            transformation = "" + String.format("%.2f", result) + ",N" + String.format("%.2f", Angle1) + "ºE";
        } else if (integers[0] < 0 && integers[1] > 0) {
            transformation = "" + String.format("%.2f", result) + ",N " + String.format("%.2f", Angle2) + "ºO";
        } else if (integers[0] < 0 && integers[1] < 0) {
            transformation = "" + String.format("%.2f", result) + ",S" + String.format("%.2f", Angle1) + "ºO";
        } else if (integers[0] > 0 && integers[1] < 0) {
            transformation = "" + String.format("%.2f", result) + ",S" + String.format("%.2f", Angle1) + "ºE";

        }
        txtResult2.setText(transformation);

        geoSpace = new GeoSpace1(integers[0],integers[1], result, numberOfTransformation);
        transform.saveRectangularToGeographicCoordinates(geoSpace);
        DefaultTableModel table;
        polar.addElement("Number of transformation");
        polar.addElement("Coordinate x");
        polar.addElement("Coordinate y");
        polar.addElement("Result");
        

    }//GEN-LAST:event_btnResultActionPerformed

    private void btnShowRectangularToGeographicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowRectangularToGeographicActionPerformed
        try {
            GeoSpaceController1 geoSpaceController = new GeoSpaceController1();
            tblGeographic.setModel(geoSpaceController.readRectangularToGeographicCoordinates());
        } catch (FileNotFoundException e) {
            Logger.getLogger(FrmGeoSpace.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnShowRectangularToGeographicActionPerformed

    private void btnFindCoordinateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCoordinateActionPerformed
        int index = 0;
        GeoSpaceController1 find = new GeoSpaceController1();
        int[] integers;
        int dataToFind;

        integers = new int[2];

        dataToFind = Integer.parseInt(txtCoordinateFind.getText());
        integers[0] = Integer.parseInt(txtRectangularCoordinateX.getText());
        integers[1] = Integer.parseInt(txtRectangularCoordinateY.getText());

        index = find.findCoordinate(dataToFind , integers);

       if (index == -1) {
            JOptionPane.showMessageDialog(null, dataToFind + " is NOT found ", "Searching", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, dataToFind + " is found ");
        }

    }//GEN-LAST:event_btnFindCoordinateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGeoSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGeoSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGeoSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGeoSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGeoSpace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnASave1;
    private javax.swing.JButton btnCoordinatePolar;
    private javax.swing.JButton btnCoordinatePolar1;
    private javax.swing.JButton btnCoordinateRectangular;
    private javax.swing.JButton btnFindCoordinate;
    private javax.swing.JButton btnFindCoordinate1;
    private javax.swing.JButton btnFindCoordinate2;
    private javax.swing.JButton btnFindCoordinate3;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveAzimut;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnShowCoordinate3;
    private javax.swing.JButton btnShowPolar1;
    private javax.swing.JButton btnShowRectangularToGeographic;
    private javax.swing.JComboBox<String> cmbOptions1;
    private javax.swing.JComboBox<String> cmbOrientation;
    private javax.swing.JButton cmbResult3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable tblCoordinatesPolar;
    private javax.swing.JTable tblCoordinatesPolar1;
    private javax.swing.JTable tblCoordinatesRectangular;
    private javax.swing.JTable tblGeographic;
    private javax.swing.JTextField txtAngle;
    private javax.swing.JTextField txtAngle1;
    private javax.swing.JTextField txtCoordinateFind;
    private javax.swing.JTextField txtCoordinateName1;
    private javax.swing.JTextField txtCoordinateNumber;
    private javax.swing.JTextField txtCoordinatePolar;
    private javax.swing.JTextField txtCoordinatePolar1;
    private javax.swing.JTextField txtCoordinateRectangular;
    private javax.swing.JTextField txtCoordinateX1;
    private javax.swing.JTextField txtCoordinateX2;
    private javax.swing.JTextField txtCoordinateY1;
    private javax.swing.JTextField txtCoordinateY2;
    private javax.swing.JTextField txtCoordinateY3;
    private javax.swing.JTextField txtCoordinateY4;
    private javax.swing.JTextField txtCoordinatex2;
    private javax.swing.JTextField txtCoordinatex3;
    private javax.swing.JTextField txtDistance;
    private javax.swing.JTextField txtDistance1;
    private javax.swing.JTextField txtFind2;
    private javax.swing.JTextField txtFindACoordinate;
    private javax.swing.JTextField txtNumberOfTransformation;
    private javax.swing.JTextField txtRectangularCoordinateX;
    private javax.swing.JTextField txtRectangularCoordinateX1;
    private javax.swing.JTextField txtRectangularCoordinateY;
    private javax.swing.JTextField txtRectangularCoordinateY1;
    private javax.swing.JTextField txtResult1;
    private javax.swing.JTextField txtResult2;
    private javax.swing.JTextField txtResult3;
    // End of variables declaration//GEN-END:variables
}
